### PR TITLE
Changed pack formats to 5 so it works with 1.15

### PR DESCRIPTION
**Pull request by grian32**
it makes the 1.14+ part of the description true

### CODE REVIEW

**Comment by misode** [comment]
@AndanteDevs This repo should match the Minecraft version of [GM4_Datapacks](https://github.com/Gamemode4Dev/GM4_Datapacks). I request this pull request to be reverted until GM4_Datapacks' master is on 1.15.

**Comment by AndanteDevs** [comment]
My viewpoint is that this pack can be used in 1.15 in combination with the current 1.14 data packs without fault. I mainly merged this so that it did not throw an error on 1.15, and the pull changes no other functionality

**Comment by misode** [comment]
Will this not be highlighted in red for 1.14?

**Comment by AndanteDevs** [comment]
I don't think so - will check

**Comment by AndanteDevs** [comment]
Oof, it does - reverting

**Pull request merged**
